version: "2.6.1"
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: punto2
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart : always
    ports :
     - 8080:8080
     
volumes:
  db:



      

